name: Dynmap-WorldGuard
main: org.dynmap.worldguard.DynmapWorldGuardPlugin
version: "${project.version}"
author: mikeprimm
depend: [ dynmap, WorldGuard ]
api-version: 1.13

libraries:
  - org.json:json:${json.version}
